mysqld:
  image: viljaste/mysqld:latest
  hostname: mysqld
  ports:
    - "3306:3306"
  volumes_from:
    - mysqlddata
  environment:
    - PASSWORD=root
mysqlddata:
  image: viljaste/data:latest
  hostname: mysqlddata
  volumes:
    - /mysqld
